fn main() {
    println!("cargo:rerun-if-changed=../../vendor/DirectoryAccess");
    println!("cargo:rerun-if-changed=../../vendor/AudioStreaming");
    tauri_plugin::Builder::new(&[
        "load",
        "control",
        "configure",
        "metadata",
        "status",
        "system_volume",
        "keep_awake",
        "airplay",
        "visibility",
        "siri",
        "read_metadata",
        "read_lyric_file",
        "register_listener",
        "remove_listener",
    ])
    .android_path("android")
    .ios_path("ios")
    .build();
}
