fn main() {
    tauri_plugin::Builder::new(&[
        "load",
        "control",
        "configure",
        "metadata",
        "status",
        "system_volume",
        "airplay",
        "visibility",
        "siri",
        "read_metadata",
        "prepare_cloud_upload",
        "upload_cloud_file",
        "register_listener",
        "remove_listener",
    ])
    .ios_path("ios")
    .build();
}
